"""Tool-definition hash pinning (SEC-022).

Computes a deterministic SHA-256 over each registered tool's **LLM-facing prompt
surface** — its ``name`` and cleaned docstring (the description the model is
steered by) — plus a single manifest hash over all of them. A committed snapshot
(``audits/tool-pins/current.json``) lets a test detect a silent change to a
tool's name or prompt text ("rug pull" / definition drift) and force a conscious
update with a CHANGELOG re-approval note.

Why not the JSON schema? The ``input``/``output`` schemas are generated by
pydantic/the MCP SDK and their serialised form changes between dependency
versions. Hashing them would make the guard fail on every benign dependency
bump (false positives), defeating the purpose. The schema/IO contract is instead
covered by the dedicated structured-output and input-validation tests. The
prompt surface hashed here is derived from our own source, so it is stable across
Python and dependency versions and only changes when *we* change a tool.

The same function powers both ``scripts/pin_tools.py`` (writes the snapshot) and
the drift test, so they can never diverge.
"""

from __future__ import annotations

import hashlib
import inspect
import json
from typing import Any


def _canonical(obj: Any) -> str:
    return json.dumps(obj, sort_keys=True, ensure_ascii=False, separators=(",", ":"))


def compute_tool_pins(mcp: Any) -> dict:
    """Return ``{"tool_count", "manifest_sha256", "tools": {name: sha256}}``.

    Deterministic across environments: the hash covers only the tool name and its
    cleaned docstring (via ``inspect.getdoc``), both sourced from our code rather
    than from version-dependent schema generation.
    """
    pins: dict[str, str] = {}
    for tool in sorted(mcp._tool_manager.list_tools(), key=lambda t: t.name):
        description = inspect.getdoc(tool.fn) or ""
        identity = _canonical({"name": tool.name, "description": description})
        pins[tool.name] = hashlib.sha256(identity.encode("utf-8")).hexdigest()

    manifest = hashlib.sha256(_canonical(pins).encode("utf-8")).hexdigest()
    return {"tool_count": len(pins), "manifest_sha256": manifest, "tools": pins}
